import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { writeFile } from 'node:fs/promises';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.UNSHIP_LIVE_URL || 'http://127.0.0.1:4173/live-canvas');
await page.waitForFunction(()=>window.__unshipPicker?.getState().groups.length===1);
const first=page.locator('[data-unship-option="Quiet start"]');
await first.locator('.increment').click();
await first.locator('input').fill('Before Canvas');
const before=await page.evaluate(()=>{
 window.originalNodes=[...document.querySelectorAll('[data-unship-option]')];
 window.originalParents=originalNodes.map(node=>node.parentNode);
 const node=originalNodes[0],r=node.getBoundingClientRect();
 return {mounts:demoMounts,shadowConnects,rect:{x:r.x,y:r.y,width:r.width,height:r.height},color:getComputedStyle(node).color,styles:originalNodes.map(n=>n.getAttribute('style'))};
});
await page.getByRole('button',{name:'Open Canvas',exact:true}).click();
await page.waitForFunction(()=>window.__unshipPicker.getState().canvas.open && getComputedStyle(document.querySelector('[data-live-option]')).visibility==='visible');
const during=await page.evaluate(()=>({sameNodes:originalNodes.every(n=>n===document.querySelector(`[data-unship-option="${n.dataset.unshipOption}"]`)),sameParents:originalNodes.every((n,i)=>n.parentNode===originalParents[i]),mounts:demoMounts,shadowConnects,iframes:document.querySelectorAll('iframe').length,color:getComputedStyle(originalNodes[0]).color,canvasPixel:[...originalNodes[0].querySelector('canvas').getContext('2d').getImageData(0,0,1,1).data],responsive:originalNodes.map(n=>({width:n.offsetWidth,viewport:getComputedStyle(n.querySelector('.media-status'),'::after').content,container:getComputedStyle(n.querySelector('.container-status'),'::after').content})),sizes:originalNodes.map(n=>({height:n.offsetHeight,width:n.offsetWidth,rect:n.getBoundingClientRect().toJSON()}))}));
console.log(JSON.stringify({before,during,errors},null,2));
await page.screenshot({path:'.unship/live-canvas/open.png',fullPage:true});
await first.locator('.increment').click({timeout:5000});
await first.locator('input').fill('Edited in Canvas');
await first.locator('.expand').click();
await first.locator('.details').waitFor();
assert.equal(await first.locator('.increment').textContent(),'Count 2');
await page.getByRole('button',{name:'Back to page',exact:true}).click();
await page.waitForFunction(()=>!window.__unshipPicker.getState().canvas.open);
const after=await page.evaluate(()=>{const n=originalNodes[0],r=n.getBoundingClientRect();return {sameParents:originalNodes.every((n,i)=>n.parentNode===originalParents[i]),mounts:demoMounts,shadowConnects,styles:originalNodes.map(n=>n.getAttribute('style')),hidden:originalNodes.map(n=>n.hidden),rect:{x:r.x,y:r.y,width:r.width,height:r.height},input:n.querySelector('input').value,count:n.querySelector('.increment').textContent,popovers:document.querySelectorAll('[data-live-option]').length};});
assert.equal(during.sameNodes,true);assert.equal(during.sameParents,true);assert.equal(during.mounts,before.mounts);assert.equal(during.shadowConnects,before.shadowConnects);assert.equal(during.iframes,2);assert.equal(during.color,before.color);assert.deepEqual(during.canvasPixel,[109,152,107,255]);assert.equal(after.input,'Edited in Canvas');assert.equal(after.count,'Count 2');assert.deepEqual(after.hidden,[false,true]);assert.deepEqual(after.styles,before.styles);assert.equal(after.popovers,0);assert.equal(after.rect.x,before.rect.x);assert.equal(after.rect.y,before.rect.y);assert.equal(after.rect.width,before.rect.width);assert.deepEqual(errors,[]);
await writeFile('.unship/live-canvas/results.json',JSON.stringify({before,during,after,errors},null,2));
console.log('PASS: live interactions, identity, React state, shadow root, canvas pixels, and restoration.');
await browser.close();
