import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { candidateVersion, compileLivePicker } from './compile.mjs';
const root = new URL('../../', import.meta.url);
const revision = execFileSync('git', ['rev-parse', 'HEAD'], {cwd: root, encoding:'utf8'}).trim();
const output = new URL(`.unship/releases/${candidateVersion}/`, root);
const stage = new URL('package/', output);
await mkdir(stage, { recursive:true });
for (const path of ['src','agent','README.md','LICENSE']) await cp(new URL(path, root), new URL(path, stage), { recursive:true });
const runtime = await compileLivePicker();
await writeFile(new URL('src/picker/unship-picker.js', stage), runtime);
const pkg = JSON.parse(await readFile(new URL('package.json', root), 'utf8'));
pkg.version = candidateVersion;
pkg.private = true;
pkg.unshipBuild = {channel:'live-canvas-local',revision,runtimeSha256:createHash('sha256').update(runtime).digest('hex')};
delete pkg.devDependencies;
delete pkg.scripts;
await writeFile(new URL('package.json', stage), JSON.stringify(pkg,null,2)+'\n');
const skillPath = new URL('agent/skills/unship/SKILL.md', stage);
let skill = await readFile(skillPath, 'utf8');
const start = skill.indexOf('## Canvas\n');
const end = skill.indexOf('## Verification and Handoff\n', start);
if (start < 0 || end < 0) throw new Error('Canvas skill section needs review');
skill = skill.slice(0,start) + await readFile(new URL('canvas-skill.md',import.meta.url),'utf8') + '\n' + skill.slice(end);
await writeFile(skillPath, skill);
const readme = new URL('README.md',stage);
await writeFile(readme, `> Local test build ${candidateVersion}. Live Canvas preserves existing components; responsive simulation is absent. External portal menus may be obscured. Unpublished; test in local development previews.\n\n${await readFile(readme,'utf8')}`);
const [pack] = JSON.parse(execFileSync('npm',['pack','--json','--pack-destination',fileURLToPath(output)],{cwd:stage,encoding:'utf8'}));
console.log(JSON.stringify({version:candidateVersion,tarball:fileURLToPath(new URL(pack.filename,output)),...pkg.unshipBuild},null,2));
